services:
  phpinfo:
    command:
      - -f
      - index.php
      - -S
      - 0.0.0.0:8080
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
    entrypoint: /usr/bin/php
    image: index.docker.io/svaziri/mycentos:latest
    ports:
      - 80:8080
    working_dir: /src
version: '3.8'
