name: ci
on:
  push:
    branches:
      - 2021-06
jobs:
  Dockerfile:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: docker image build --file Dockerfile --tag index.docker.io/svaziri/mycentos:test ${PWD}
      - name: history
        run: docker image history index.docker.io/svaziri/mycentos:test
      - name: run
        run: docker container run --detach --entrypoint php --name php-test --workdir /src --rm index.docker.io/svaziri/mycentos:test  -S 0.0.0.0:8080
      - name: logs
        run: while true ; do sleep 10 && docker container logs php-test 2>& 1 | grep 'Development Server (http://0.0.0.0:8080) started' && break ; done
