name: ci
on:
  push:
    branches:
      - 2021-06
jobs:
  Dockerfile:
    runs-on: ubuntu-18.04
    steps:
     - name: checkout
        uses: actions/checkout@v2
     - name: build
        run: docker image build --file Dockerfile --tag index.docker.io/svaziri/simplilearn-phpinfo:test ${PWD}
     - name: history
        run: docker image history index.docker.io/academiaonline/simplilearn-phpinfo:test
     - name: run
        run: docker container run --detach --entrypoint php --name php-test --rm index.docker.io/academiaonline/simplilearn-phpinfo:test -f src/index.php -S 0.0.0.0:8080
     - name: top
        run: while true ; do sleep 10 && docker container top php-test 2>& 1 | grep 'php -f src/index.php -S 0.0.0.0:8080' && break ; done
     - name: log
        run: while true ; do sleep 10 && docker container log php-test 2>& 1 | grep 'started' && break ; done
        
